CREATE DATABASE wikiemploi_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER 'wikiman'@'localhost' IDENTIFIED BY 'wikiman';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON wikiemploi_db.* TO 'wikiman'@'localhost' IDENTIFIED BY 'wikiman' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
// GRANT ALL ON wikiemploi_db TO 'wikiman@localhost' IDENTIFIED BY wikiman;